# Generated by Django 6.0.4 on 2026-04-22 11:46

import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedocument',
            name='file',
            field=models.FileField(upload_to='resumes/', validators=[profiles.validators.validate_resume_pdf_file]),
        ),
    ]
