# Generated by Django 6.0.4 on 2026-04-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
