# Generated by Django 6.0.4 on 2026-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountprofile_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
